export type Ticket={id:string;customer:string;subject:string;language:string;intent:string;priority:"urgent"|"normal"|"low";received:string;message:string;translation:string;confidence:number};
export const tickets:Ticket[]=[
 {id:"m-1042",customer:"Sofia Martin",subject:"Unable to export the audit report",language:"French",intent:"Technical issue",priority:"urgent",received:"4 min",message:"Bonjour, l’export PDF reste bloqué à 92 % depuis ce matin. Nous devons transmettre le rapport à notre auditeur aujourd’hui.",translation:"你好，PDF 导出从今天早上开始一直卡在 92%。我们今天必须把报告交给审计方。",confidence:98},
 {id:"m-1041",customer:"Kenji Watanabe",subject:"Question about annual billing",language:"Japanese",intent:"Billing",priority:"normal",received:"18 min",message:"年間プランに変更した場合、現在の月額プランの残りはどのように精算されますか？",translation:"如果改为年度套餐，目前月度套餐剩余金额将如何结算？",confidence:96},
 {id:"m-1039",customer:"Maya Patel",subject:"Invite permissions for contractors",language:"English",intent:"How-to",priority:"normal",received:"1 hr",message:"Can contractors be limited to one workspace without seeing our other client projects?",translation:"能否将外包人员限制在单个工作区，使其无法查看其他客户项目？",confidence:99},
 {id:"m-1038",customer:"Diego Ramos",subject:"Solicitud de eliminación de datos",language:"Spanish",intent:"Privacy request",priority:"urgent",received:"2 hr",message:"Quiero eliminar mi cuenta y todos los datos asociados. ¿Podrían confirmar el plazo?",translation:"我想删除账户及所有关联数据，请确认处理期限。",confidence:99}
];
export function sortTickets(rows:Ticket[]){const rank={urgent:0,normal:1,low:2};return [...rows].sort((a,b)=>rank[a.priority]-rank[b.priority]);}
export function groundedDraft(ticket:Ticket){return {subject:`Re: ${ticket.subject}`,body:ticket.intent==="Technical issue"?"Hi Sofia,\n\nI’m sorry the export is blocking your audit deadline. I’ve logged this as an urgent incident. Please keep the affected report unchanged while we investigate; I’ll update you with a concrete next step within 30 minutes.\n\nBest,\nSupport team":ticket.intent==="Privacy request"?"Hi Diego,\n\nWe’ve received your deletion request. Before processing it, we need to verify account ownership through the secure account flow. We won’t ask you to send identity documents by email.\n\nBest,\nPrivacy team":"Thanks for reaching out. I’ve reviewed your question and prepared the relevant steps below. A support specialist will verify the account-specific details before sending.",citations:["Support SLA §2.1","Account security policy §4"],requiresApproval:true};}
