"use client";
import { useMemo, useState } from "react";
import { filterOpportunities, opportunities, type Opportunity } from "@/lib/opportunities";

const Icon=({children}:{children:React.ReactNode})=><span className="icon">{children}</span>;

export default function Home(){
  const [query,setQuery]=useState(""); const [source,setSource]=useState("All sources"); const [selected,setSelected]=useState<Opportunity>(opportunities[0]); const [saved,setSaved]=useState<string[]>(["northstar"]); const [panel,setPanel]=useState<"details"|"proposal">("details");
  const visible=useMemo(()=>filterOpportunities(opportunities,query,source),[query,source]);
  const save=(id:string)=>setSaved(value=>value.includes(id)?value.filter(x=>x!==id):[...value,id]);
  return <main>
    <aside className="rail"><div className="mark">F<span>O</span></div><nav><button className="active"><Icon>⌁</Icon>Discover</button><button><Icon>◫</Icon>Pipeline <b>3</b></button><button><Icon>✦</Icon>AI Studio</button><button><Icon>⌘</Icon>Automations</button></nav><div className="rail-bottom"><button><Icon>?</Icon>Docs</button><div className="avatar">RC</div><div><strong>Portfolio Demo</strong><small>Privacy-safe mode</small></div></div></aside>
    <section className="workspace">
      <header><div><p className="eyebrow">OPPORTUNITY INTELLIGENCE</p><h1>Find work worth doing.</h1><p>One focused pipeline for discovering, evaluating and winning technical freelance work.</p></div><div className="live"><i/>LIVE SOURCES <strong>12</strong></div></header>
      <div className="metrics"><article><small>HIGH MATCH</small><b>14</b><em>+6 this week</em></article><article><small>OPEN PIPELINE</small><b>$32.5k</b><em>5 proposals</em></article><article><small>RESPONSE RATE</small><b>38%</b><em>↑ 12%</em></article><article><small>TIME SAVED</small><b>11.4h</b><em>this month</em></article></div>
      <div className="toolbar"><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search roles, companies or skills…"/></label><select value={source} onChange={e=>setSource(e.target.value)}><option>All sources</option><option>Y Combinator</option><option>Wellfound</option><option>Hacker News</option><option>GitHub</option></select><button className="filter">⚙ Filters <span>2</span></button></div>
      <div className="content"><section className="list"><div className="list-title"><b>{visible.length} curated opportunities</b><span>Ranked by fit and freshness</span></div>{visible.map(item=><article key={item.id} className={`job ${selected.id===item.id?"selected":""}`} onClick={()=>{setSelected(item);setPanel("details")}}><i className="company" style={{background:item.accent}}>{item.company[0]}</i><div className="job-main"><div><small>{item.company}</small><h2>{item.role}</h2></div><p>{item.summary}</p><div className="chips">{item.skills.map(x=><span key={x}>{x}</span>)}</div><footer><span>{item.source}</span><span>◷ {item.posted}</span><span>◎ {item.location}</span></footer></div><div className="job-side"><button onClick={e=>{e.stopPropagation();save(item.id)}} aria-label="Save">{saved.includes(item.id)?"★":"☆"}</button><strong>{item.match}%</strong><small>match</small><b>{item.budget}</b><em>{item.type}</em></div></article>)}</section>
      <aside className="inspector"><div className="tabs"><button className={panel==="details"?"active":""} onClick={()=>setPanel("details")}>Analysis</button><button className={panel==="proposal"?"active":""} onClick={()=>setPanel("proposal")}>AI proposal</button></div>{panel==="details"?<><div className="score"><div><span>{selected.match}</span><small>/100</small></div><p><b>Excellent fit</b><span>Strong overlap with your verified skills and preferred work style.</span></p></div><h3>Why it matches</h3><ul className="reasons"><li><i>✓</i><span><b>Technical overlap</b>3 core skills match this brief</span></li><li><i>✓</i><span><b>Remote compatible</b>{selected.location}</span></li><li><i>✓</i><span><b>Rate alignment</b>Within preferred contract range</span></li></ul><h3>Suggested positioning</h3><p className="positioning">Lead with production delivery experience, then offer a small paid discovery milestone to reduce scope risk.</p><button className="primary" onClick={()=>setPanel("proposal")}>✦ Generate tailored proposal</button><button className="secondary">Open original listing ↗</button></>:<><div className="proposal-head"><span>✦</span><div><h3>Tailored proposal</h3><p>Grounded in verified portfolio facts</p></div></div><div className="draft"><small>OPENING</small><p>I can help {selected.company} deliver this without turning the first milestone into a long architecture exercise.</p><small>PROOF POINTS</small><ul>{selected.skills.map(x=><li key={x}>Production experience with {x}</li>)}</ul><small>PLAN</small><p>Start with a scoped technical audit, agree on measurable acceptance criteria, then ship the highest-risk path first.</p></div><div className="safety">✓ No invented experience or unverified claims</div><button className="primary">Copy proposal</button><button className="secondary" onClick={()=>setPanel("details")}>Back to analysis</button></>}</aside></div>
    </section>
  </main>;
}
