"use client";
import { FormEvent,useEffect,useState } from "react";
type Item={id:string;title:string;summary:string;link:string;skills:string[];evidence:string;position:number};
const empty={title:"",summary:"",link:"",skills:"",evidence:""};
export default function PortfolioBuilder(){
 const [items,setItems]=useState<Item[]>([]),[form,setForm]=useState(empty),[notice,setNotice]=useState("");
 const load=async()=>{const r=await fetch("/api/portfolio",{cache:"no-store"});if(r.ok)setItems((await r.json()).items||[]);};useEffect(()=>{load();},[]);
 const save=async(e:FormEvent)=>{e.preventDefault();setNotice("正在保存…");const r=await fetch("/api/portfolio",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,skills:form.skills.split(",").map(x=>x.trim()).filter(Boolean),position:items.length})});if(r.ok){setForm(empty);setNotice("已保存到私有工作台");await load();}else setNotice("保存失败，请检查标题、说明和链接");};
 const remove=async(id:string)=>{const r=await fetch(`/api/portfolio?id=${encodeURIComponent(id)}`,{method:"DELETE"});if(r.ok)await load();};
 return <div className="profile-page"><section className="profile-hero"><div className="avatar">私</div><div><h2>私有申请资料</h2><p>仅登录后读取 · 不写入公开代码</p><span>项目证据由私有数据库保存</span></div></section><section className="profile-card"><h3>Portfolio Builder</h3><p className="profile-hint">只填写可核验事实；不会从已删除材料自动导入内容。</p><form onSubmit={save} className="portfolio-form"><input required placeholder="项目标题" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea required placeholder="项目说明与本人贡献" value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/><input placeholder="作品或仓库链接（HTTPS）" value={form.link} onChange={e=>setForm({...form,link:e.target.value})}/><input placeholder="技能，以逗号分隔" value={form.skills} onChange={e=>setForm({...form,skills:e.target.value})}/><textarea placeholder="可核验证据或验收结果" value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})}/><button className="oauth-connect" type="submit">保存项目</button></form>{notice&&<p className="application-note">{notice}</p>}</section><section className="profile-card"><h3>已保存项目</h3>{items.length?items.map(item=><article className="portfolio-item" key={item.id}><h4>{item.title}</h4><p>{item.summary}</p><div className="profile-skills">{item.skills.map(skill=><span key={skill}>{skill}</span>)}</div>{item.link&&<a href={item.link} target="_blank" rel="noreferrer">查看证据链接 ↗</a>}<button className="danger-action" onClick={()=>remove(item.id)}>删除</button></article>):<p className="profile-hint">尚未保存项目。</p>}</section></div>;
}
