import { getChatGPTUser } from "../../../chatgpt-auth";
import { db,ensureDatabase } from "../../../../db";
import { unseal } from "../../../../lib/secret-store";

const headers=(token:string)=>({Authorization:`Bearer ${token}`,Accept:"application/vnd.github+json","Content-Type":"application/json","X-GitHub-Api-Version":"2022-11-28"});
const escape=(value:unknown)=>String(value||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
async function putFile(token:string,owner:string,repo:string,path:string,content:string,message:string){
  const endpoint=`https://api.github.com/repos/${owner}/${repo}/contents/${path}`;
  const current=await fetch(endpoint,{headers:headers(token),cache:"no-store"});
  const existing=current.ok?await current.json() as {sha?:string}:{};
  const response=await fetch(endpoint,{method:"PUT",headers:headers(token),body:JSON.stringify({message,content:Buffer.from(content).toString("base64"),branch:"main",...(existing.sha?{sha:existing.sha}:{})}),cache:"no-store"});
  if(!response.ok)throw new Error(`github_file_${response.status}`);
}
export async function POST(){
  const user=await getChatGPTUser();if(!user)return Response.json({error:"sign_in_required"},{status:401});
  await ensureDatabase();const sql=db();
  const [connections,items]=await Promise.all([
    sql`SELECT account_label AS "accountLabel",token_ciphertext AS "tokenCiphertext" FROM channel_connections WHERE owner_email=${user.email} AND provider=${"github"} AND status=${"connected"} LIMIT 1`,
    sql`SELECT title,summary,link,skills,evidence FROM portfolio_items WHERE owner_email=${user.email} ORDER BY position ASC,updated_at DESC`,
  ]);
  const connection=connections[0] as any;if(!connection?.tokenCiphertext)return Response.json({error:"github_authorization_required"},{status:409});
  const token=await unseal(String(connection.tokenCiphertext)),owner=String(connection.accountLabel),repo="ruozhu-portfolio";
  let portfolioItems=items as any[];
  if(!portfolioItems.length){
    const verifiedRepo=`https://github.com/${owner}/remote-gig-desk-vercel`,now=Date.now(),id=crypto.randomUUID(),skills=JSON.stringify(["Next.js","TypeScript","PostgreSQL","Playwright","Vercel"]),summary="A production remote-work opportunity desk with verified-source aggregation, individualized application materials, Gmail response tracking, ATS browser execution, evidence-gated submission status, and portfolio publishing.";
    await sql`INSERT INTO portfolio_items(id,owner_email,title,summary,link,skills,evidence,position,status,created_at,updated_at) VALUES(${id},${user.email},${"Remote Gig Desk"},${summary},${verifiedRepo},${skills}::jsonb,${"Public source repository and live production deployment"},${0},${"verified"},${now},${now})`;
    portfolioItems=[{title:"Remote Gig Desk",summary,link:verifiedRepo,skills:["Next.js","TypeScript","PostgreSQL","Playwright","Vercel"],evidence:"Public source repository and live production deployment"}];
  }
  const repoResponse=await fetch("https://api.github.com/user/repos",{method:"POST",headers:headers(token),body:JSON.stringify({name:repo,description:"Verified engineering portfolio generated by Remote Gig Desk",private:false,auto_init:true}),cache:"no-store"});
  if(!repoResponse.ok&&repoResponse.status!==422)return Response.json({error:`github_repo_${repoResponse.status}`},{status:502});
  if(repoResponse.ok)await new Promise(resolve=>setTimeout(resolve,1200));
  const cards=portfolioItems.map(item=>`<article><h2>${escape(item.title)}</h2><p>${escape(item.summary)}</p><div>${(item.skills||[]).map((skill:string)=>`<span>${escape(skill)}</span>`).join("")}</div>${item.evidence?`<p class="evidence"><b>Evidence:</b> ${escape(item.evidence)}</p>`:""}${item.link?`<a href="${escape(item.link)}" rel="noreferrer">View verified project ↗</a>`:""}</article>`).join("");
  const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ruozhu Chen · Engineering Portfolio</title><style>body{margin:0;background:#f4f8f6;color:#14251d;font:16px system-ui}main{max-width:900px;margin:auto;padding:64px 20px}header{margin-bottom:36px}h1{font-size:42px;margin:0}header p{color:#607269}article{background:white;border:1px solid #d9e5df;border-radius:18px;padding:24px;margin:18px 0;box-shadow:0 10px 30px #173b2a0d}article p{line-height:1.7;color:#52645b}span{display:inline-block;background:#e9f6ef;color:#087551;border-radius:99px;padding:6px 10px;margin:4px;font-size:13px}a{display:inline-block;margin-top:12px;color:#087551;font-weight:700}.evidence{border-left:3px solid #27a877;padding-left:12px}</style><main><header><h1>Engineering Portfolio</h1><p>Selected projects with explicit evidence and source links. No fabricated client data.</p></header>${cards}</main></html>`;
  const readme=`# Ruozhu Chen — Engineering Portfolio\n\nThis repository is generated from verified portfolio items. It intentionally excludes private profile, résumé, email, and application data.\n\n${portfolioItems.map(item=>`## ${item.title}\n\n${item.summary}\n\n${item.link?`[Evidence link](${item.link})`:""}`).join("\n\n")}`;
  try{await putFile(token,owner,repo,"index.html",html,"Publish verified portfolio");await putFile(token,owner,repo,"README.md",readme,"Update portfolio README");}
  catch(error){return Response.json({error:error instanceof Error?error.message:"github_publish_failed"},{status:502});}
  const pages=await fetch(`https://api.github.com/repos/${owner}/${repo}/pages`,{method:"POST",headers:headers(token),body:JSON.stringify({source:{branch:"main",path:"/"}}),cache:"no-store"});
  if(!pages.ok&&pages.status!==409&&pages.status!==422)return Response.json({error:`github_pages_${pages.status}`},{status:502});
  const githubRepo=`https://github.com/${owner}/${repo}`,deploymentUrl=`https://${owner.toLowerCase()}.github.io/${repo}/`,now=Date.now();
  await sql`UPDATE portfolio_items SET github_repo=${githubRepo},deployment_url=${deploymentUrl},status=${"published"},updated_at=${now} WHERE owner_email=${user.email}`;
  return Response.json({githubRepo,deploymentUrl,status:"published"});
}
